### ISSUE TITLE
Implement LESS for the Yeti template

### ISSUE THREAD

**Issue by GregTurner** [BCDevX/BCDevX.github.io-src#13]
And if appropriate, implement the custom styles via LESS.

**Comment by annacox** [comment]
addressed with commits: 1354290f227a5da53f1f50c81f413821481a0024, 751cb5c5ea372dce281f7fda537099a3d1c6a2c5, 0306c32853ca8cbcc7025e4a9034643c6698ce43, 093a28adea12f479fa536f0527ee574c2306a893, 461d48f8a5039172fecd5e6cf8d1e6ab63c45517
