### ISSUE TITLE
Intro text wording

### ISSUE THREAD

**Issue by GregTurner** [BCDevX/BCDevX.github.io-src#2]
Original text:
British Columbia Developer Exchange (BCDevX) is intended to enhance collaboration between Government, Broader Public Sector, and Industry, to allow for the sharing of digital resources and knowledge, and to help stimulate innovation and technology growth in BC.

Proposed:
*The British Columbia Developers' Exchange (BCDevX) mission is* to enhance collaboration between Industry, Broader Public Sector, and Government, to allow for the sharing of digital resources and knowledge, and to help stimulate innovation and technology growth in BC.

Change the Developers' everywhere!

**Comment by annacox** [comment]
Leaving this issue for the wording. I've opened #10 for changing the logo.
